### ISSUE TITLE
Reihenfolge Verknüpfte Medientypen wenn nur min-width verwendet wird (wie empfohlen)

### ISSUE THREAD

**Issue by ynamite** [alexplusde/media_manager_responsive#16]
Die verknpüften Medientypen müssen in Bezug auf `min-width` von gross nach klein (zuerst die höchste min-width) sortiert werden, damit die korrekte grösse geladen wird (zumindest in Firefox und gemäss Picture bzw. Source Spezifikation, siehe https://html.spec.whatwg.org/multipage/embedded-content.html#attr-source-media und https://stackoverflow.com/a/41063084).

`the browser goes over the list of sources and picks the first one that matches. `

**Funktioniert nicht**
```
<picture>
  <source media="all AND (min-width: 1px)" sizes="" type="image/jpeg" data-width="400" data-height="105"
    srcset="/media/bild-md/bild.jpg?timestamp=1674658426">
  <source media="all AND (min-width: 480px)" sizes="" type="image/jpeg" data-width="800" data-height="210"
    srcset="/media/bild-xl/bild.jpg?timestamp=1674658426">
    <img type="image/jpeg"
    src="/media/bild-sm/bild.jpg?timestamp=1674658426" alt="" loading="lazy" width="400" height="105">
</picture>
```

**Funktioniert**
```
<picture>
  <source media="all AND (min-width: 480px)" sizes="" type="image/jpeg" data-width="800" data-height="210"
    srcset="/media/bild-xl/bild.jpg?timestamp=1674658426">
  <source media="all AND (min-width: 1px)" sizes="" type="image/jpeg" data-width="400" data-height="105"
    srcset="/media/bild-md/bild.jpg?timestamp=1674658426">
    <img type="image/jpeg"
    src="/media/bild-sm/bild.jpg?timestamp=1674658426" alt="" loading="lazy" width="400" height="105">
</picture>
```

Wahrscheinlich ist dir das klar, aber die Hilfeseite des Addons erklärt das nicht und bin erst selbst darüber gestolpert.

**Comment by alxndr-w** [comment]
Genau. Darüber habe ich mir auch schon den Kopf zerbrochen. 

ich bin da noch nicht zu einem einheitlichen Schema gekommen, denn je nachdem, was man als min/max einträgt oder frei lässt und ob man diese nochmal mit anderen Dateiformaten und Retina-Einstellungen kombiniert, ist eine automatisierte Sortierung quasi nicht umzusetzen.

Wie würdest du das lösen?

**Comment by ynamite** [comment]
Ich stimme dir zu, automatisch lösen lässt sich das glaube ich nicht. 
Ich denke ein Hinweis in der Doku, wie der Browser vorgeht um das passende Bild zuwählen, würde reichen.

**Comment by alxndr-w** [comment]
duplicate #16
