### ISSUE TITLE
alt-Text überschreiben

### ISSUE THREAD

**Issue by ynamite** [alexplusde/media_manager_responsive#17]
Es wäre sehr nützlich wenn man den alt-Text beim Bildaufruf überschreiben könnte. Standardmässig wird ja der Bildtitel aus dem Medienpool geladen, manchmal ist es aber hilfreich, wenn man den benutzerdefiniert setzen könnte. Sowas in der Art:

```
rex_media_plus::get($entry['img'])->setAltText('Meine benutzerdefinierter Alt-Text')->getPicture('news-home');
```

oder so ähnlich

**Comment by alxndr-w** [comment]
Bin ich absolut deiner Meinung. Dazu komme ich im Moment nicht, ein PR oder gesponserte Entwicklungszeit würden helfen.

Ich würde gerne ohnehin die Ausgabe in Fragmente auslagern, dann kann bei Bedarf nochmal die genaue Ausgabe darüber gesteuert werden. Vorbereitet ist es bereits. https://github.com/alexplusde/media_manager_responsive/tree/main/fragments/media_manager_responsive

**Comment by ynamite** [comment]
Klingt gut. Ich schau mir das mal an 👍🏼

**Comment by alxndr-w** [comment]
@ynamite wie schaut's da so aktuell aus? :)

**Comment by ynamite** [comment]
Ich schau mir das die Tage an, versprochen. Better late than never :)

**Comment by ynamite** [comment]
https://github.com/alexplusde/media_manager_responsive/compare/main...ynamite:media_manager_responsive:patch-2

**Comment by alxndr-w** [comment]
Ah, die Property gibt's ja bereits in der   Elternklasse. So einfach war's.

**Comment by ynamite** [comment]
Habe selbst nicht schlecht gestaunt, super einfach 😅
