### ISSUE TITLE
`loading="lazy"` Support

### ISSUE THREAD

**Issue by ynamite** [alexplusde/media_manager_responsive#18]
Native Lazyloading wäre ebenfalls ein cooles Feature :)

**Comment by alxndr-w** [comment]
Ich könnte schwören, ich wurde neulich schon mal darauf angesprochen und hatte das schon drin - nur an einer Stelle nicht.

Bin ich absolut deiner Meinung. Nur auch dazu komme ich im Moment nicht, ein PR oder gesponserte Entwicklungszeit würden helfen.

**Comment by ynamite** [comment]
👍🏼

**Comment by alxndr-w** [comment]
Schau mal nach der Methode `setLoading()` - die macht eigentlich genau das.

**Comment by ynamite** [comment]
Stimmt. Sehe ich das richtig, dass der Getter aktuell nirgends verwendet wird?

**Comment by alxndr-w** [comment]
Das wird es sein. Sorry 🤷‍♂️ wenn du möchtest, bau es direkt ein für die passenden Methoden (picture, img)

**Comment by alxndr-w** [comment]
Zur besseren Steuerung und weil ich mir noch einen Automatismus überlegt habe...

**Comment by alxndr-w** [comment]
Keiner möchte?
