### ISSUE TITLE
Fehler beim Aufruf der Funktion rex_media_plus::get("beispielbild.jpg")->getPicture($group);

### ISSUE THREAD

**Issue by engel4u** [alexplusde/media_manager_responsive#20]
In der aktuellen Version kommt es zu einem Fehler beim Aufruf der Funktion "rex_media_plus::get". 

In der Version 1.0.1 habe ich ein Bild wie folgt in einem Modul eingebunden / ausgegeben:

```
$media = rex_media_plus::get("REX_MEDIA[1]"); 
$fe_img = $media->getPicture('bxslider'); 
```

Lt. Doku erfolgt die Einbindung wie folgt:
`rex_media_plus::get("beispielbild.jpg")->getPicture($group);`

Konkret heißt das: 
`$media = rex_media_plus::get("REX_MEDIA[1]")->getPicture('bxslider'); `

Im Frontend wird der folgende Fehler angezeigt:

**TypeError thrown with message "implode(): Argument #2 ($array) must be of type ?array, string given"**

PHP 8.0.27, Redaxo 5.14.2)

**Comment by alxndr-w** [comment]
Prüf mal bitte, ob du eine Gruppe namens "bxslider" angelegt hast und ob diese Bildprofile zugewiesen bekommen hat.

Es sieht nämlich danach aus, als ob `implode()` nur dann fehlschlägt, wenn nichts gefunden wurde.

https://github.com/alexplusde/media_manager_responsive/blob/adb983d456dd75a4ae3d9241cc59d9cc56e829b2/lib/media_manager_type_group.php#L63-L70
