### ISSUE TITLE
Methode getSvg() knallt wegen PHP_EOL Typo

### ISSUE THREAD

**Issue by godsdog** [alexplusde/media_manager_responsive#23]
PR ist erstellt.

https://github.com/alexplusde/media_manager_responsive/pull/22

**Comment by alxndr-w** [comment]
Tipp: schreib in den PR `close #22`, also die ID des issues, dann würde das Issue automatisch geschlossen werden.

In jedem Fall danke;

**Comment by godsdog** [comment]
Wieder was gelernt. Danke für den Tipp!
