### ISSUE TITLE
Nach Update auf 1.1.2: rex_media_plus::getAttributes(): Return value must be of type array, null returned

### ISSUE THREAD

**Issue by godsdog** [alexplusde/media_manager_responsive#25]
Es whoopst:

`rex_media_plus::getAttributes(): Return value must be of type array, null returned`.
So richtig raffe ich nicht warum?!

Aufruf:
`echo rex_media_plus::get('entw_07_697x383.jpg')->getPicture('highlight-nav');`

**Comment by godsdog** [comment]
Damit gehts wieder:

`    public function getAttributes() :array
    {
        if ($this->attributes === null) {
            return [];
        }

        return $this->attributes;
    }`

**Comment by alxndr-w** [comment]
Ich muss zugeben, ein paar Dinge bei der Typisierung habe ich nicht im Blick. Probier mal bitte

```
public function getAttributes() : ?array
    {
        return $this->attributes;
    }
```

**Comment by alxndr-w** [comment]
Mir unerklärlich, warum da null zurück gegeben wird. Sorry für die Umstände, falls das auf mich zurück zu führen ist.

**Comment by godsdog** [comment]
Mit:
```
public function getAttributes() : ?array
    {
        return $this->attributes;
    }
```

whoopst es dan: 
bei:
```
if ($cached_media instanceof rex_managed_media) {
                $picture[] = '<img '.implode(' ', $media_plus->getAttributes()).' class="'.$media_plus->getClass().'" type="image/'.$cached_media->getFormat().'" src="'.rex_media_plus::getFrontendUrl($cached_media, $group->getFallback(), $file).'" width="'.$cached_media->getWidth().'" height="'.$cached_media->getHeight().'" alt="'.$media_plus->getTitle().'" />';
            }
```

`implode(): Argument #1 ($pieces) must be of type array, string given`

**Comment by alxndr-w** [comment]
Welche PHP-Version nutzt du?

**Comment by godsdog** [comment]
8.1.16

**Comment by alxndr-w** [comment]
Also hier wird eigentlich das leere Array als property definiert:

https://github.com/alexplusde/media_manager_responsive/blob/7e6ede5bca857da5de855e93ddbeddd13ffa374f/lib/rex_media_plus.php#L7

Folglich muss es auch nicht in die constructor-Methode.

Dass implode() den 1. Parameter bemängelt - offenkundig wie gewünscht einen String - lässt mich an meinem Verstand zweifeln.

**Comment by godsdog** [comment]
Hmm, also vor dem Update lief es, auch schon mit PHP 8.1.16. Hatte gerade auch noch das neuste Redaxo Update (5.15.1) gemacht. Evtl. hat es damit was zu tun?! Fakt ist, dass beim Initiieren der Klasse die Variable $attributes nicht gesetzt wird.

**Comment by godsdog** [comment]
Mich wundert es eh, dass die Variable puplic ist?! Es gibt ja einen getter und setter.

**Comment by alxndr-w** [comment]
@godsdog daran merkste halt, dass ich hemdsärmelig programmieren gelernt habe und lerne...

**Comment by godsdog** [comment]
Hehe ich habe auch nur gefährliches 3/4 Wissen :)
Ich schaue mir das die Tage noch mal an...

**Comment by alxndr-w** [comment]
Ich hab's jetzt anders korrigiert. Aber ich sag mal so: Dass attributes da überschrieben wird, stellt für mich die Frage, ob überhaupt da drin je was sinnvolles stehen kann.
