### ISSUE TITLE
whooops nach update auf 1.1.2

### ISSUE THREAD

**Issue by ynamite** [alexplusde/media_manager_responsive#27]
Whooops nach update im Backend, danach nur noch im Safe-Mode aufrufbar.

Statt ```public function setClass(:string $class)```
müsste es  ```public function setClass($class) :string``` sein.
Nachdem ich das manuell angepasst habe, klappt's wieder :)

**ParseError:** syntax error, unexpected token ":", expecting variable
**File:** redaxo/src/addons/media_manager_responsive/lib/rex_media_plus.php
**Line:** 26

<details>
<summary>Stacktrace</summary>

| Function                 | File                                                | Line     |
| ------------------------ | --------------------------------------------------- | -------- |
| rex_autoload::autoload   | redaxo/src/core/lib/extension.php                   | 78       |
| rex_extension::register  | redaxo/src/addons/media_manager_responsive/boot.php | 15       |
| require                  | redaxo/src/core/lib/packages/package.php            | 233      |
| rex_package->includeFile | redaxo/src/core/lib/packages/package.php            | 395      |
| rex_package->boot        | redaxo/src/core/packages.php                        | 25       |
| {closure}                | redaxo/src/core/lib/util/timer.php                  | 62       |
| rex_timer::measure       | redaxo/src/core/packages.php                        | 24       |
| {closure}                | redaxo/src/core/lib/util/timer.php                  | 62       |
| rex_timer::measure       | redaxo/src/core/packages.php                        | 22       |
| include_once             | redaxo/src/core/backend.php                         | 199      |
| require                  | redaxo/src/core/boot.php                            | 155      |
| require                  | redaxo/index.php                                    | 10       |

</details>
<details>
<summary>System report (REDAXO 5.15.1, PHP 8.2.3, MariaDB 10.3.38)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.1     |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 8.2.3                          |
|       OPcache | yes                            |
|        Xdebug | no                             |
|       Warning | Das Setup wird unverschlüsselt durchgeführt. Frontend und Backend sollten grundsätzlich durch HTTPS verschlüsselt aufgerufen werden, um die Privatsphäre zu schützen und den Datenschutz zu gewährleisten. |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.3.38 |
| Character set | utf8            |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |               |
| ------------: | :------------ |
|       Browser | Firefox/111.0 |
|      Protocol | HTTP/1.0      |
|         HTTPS | no            |

| Packages                          |            |
| --------------------------------: | :--------- |
|                           adminer | 1.9.3      |
|                   article_presets | 1.2.0      |
|                            backup | 2.9.0      |
|                       be_password | 2.0.1      |
|                          be_style | 3.2.0      |
|               be_style/customizer | 3.2.0      |
|                   be_style/redaxo | 3.2.0      |
|                          be_tools | 1.7.8      |
|                           bloecks | 3.1.1      |
|                  bloecks/cutncopy | 3.1.1      |
|                 bloecks/dragndrop | 3.1.1      |
|                    bloecks/status | 3.1.1      |
|                     clear_content | 1.1.1      |
|                   consent_manager | 4.0.3      |
|                           cropper | 1.4.0      |
|                         developer | 3.9.2      |
|                        focuspoint | 4.0.4      |
|                        hyphenator | 1.3.0      |
|                           install | 2.11.1     |
|                            massif | 1.0.0      |
|                     massif_minify | 1.3.2      |
|                   massif_settings | 1.0.0      |
|                            mblock | 3.4.12     |
|                     media_manager | 2.14.0     |
|          media_manager_responsive | 1.1.2      |
|                  media_negotiator | 2.0.0      |
|                         mediapool | 2.13.0     |
|                          metainfo | 2.10.0     |
|                             mform | 7.2.7      |
|                         phpmailer | 2.12.0     |
|                              plyr | 3.20.5     |
|                           project | dev        |
|                          speed_up | 1.3.1      |
|                             sprog | 1.5.1      |
|                        statistics | 2.4.0      |
|                  statistics/media | 2.4.0      |
|                         structure | 2.15.0     |
|                 structure/content | 2.15.0     |
|                 structure/history | 2.15.0     |
|                  structure_tweaks | 1.4.0      |
|                             theme | 1.3.3      |
|                        theme_lock | 1.0.0      |
|                          tinymce5 | 1.2.17     |
|                          ui_tools | 1.2.2      |
| ui_tools/bootstrap-datetimepicker | 4.17.47    |
|        ui_tools/jquery-minicolors | 2.4.0      |
|                ui_tools/selectize | 0.2.0      |
|                          uploader | 2.4.1      |
|                               url | 2.1.0      |
|                         useragent | 2.3.0      |
|                             users | 2.10.0     |
|                             yform | 4.1.0      |
|                       yform/email | 4.1.0      |
|                     yform/manager | 4.1.0      |
|                       yform/tools | 4.1.0      |
|                     yform_adminer | 1.2.0      |
|                     yform_geo_osm | 1.2.8      |
|                  yform_quick_edit | 1.0.1      |
|             yform_spam_protection | 2.0-beta4  |
|                   yform_usability | 2.0.9      |
|                          yrewrite | 2.9.1      |

</details>

**Comment by alxndr-w** [comment]
#26
