### ISSUE TITLE
media_manager_type_meta::getMinWidth(): Return value must be of type int, string returned

### ISSUE THREAD

**Issue by godsdog** [alexplusde/media_manager_responsive#35]
Es knallt mit der neusten Version:
/redaxo/src/addons/media_manager_responsive/lib/media_manager_type_meta.php:18
`media_manager_type_meta::getMinWidth(): Return value must be of type int, string returned`

Wenn ich auf :string caste knallt es danach woanders...

Guckst du drüber oder soll ich mich reinfuchsen?

PHP: 8.1.27
Redaxo: 5.17.1

**Comment by alxndr-w** [comment]
Probiere Mal bitte den fix in #35

**Comment by godsdog** [comment]
Läuft in Verbidnung mit meinem [PR](https://github.com/alexplusde/media_manager_responsive/pull/37) :)
